FROM ubuntu:18.04

MAINTAINER Rodrigo de Souza "rsouza01@gmail.com"
LABEL Author="Rodrigo de Souza"
LABEL E-mail="rsouza01@gmail.com"
LABEL version="0.0.1"


RUN apt-get update && apt-get upgrade -y && apt-get clean

ENV DOCKER_CONTAINER true

RUN apt-get install -y curl python3.7 python3.7-dev python3.7-distutils
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
RUN update-alternatives --set python /usr/bin/python3.7
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./CICD/tests.sh /app/tests.sh
COPY ./astroimages_file_drivers /app/astroimages_file_drivers
COPY ./test /app/test

RUN chmod +x tests.sh

ENV PYTHONPATH "${PYTHONPATH}:./astroimages_file_drivers"

CMD /app/tests.sh